name: release
on: 
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: golang:1.19.0-bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: vet
        run: go vet
      - name: test
        run: go test -v

  release:
    needs: test
    runs-on: ubuntu-22.04
    container: golang:1.19.0-bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
