name: release
on: 
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: golang:1.19.0-bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: go test -v

  build:
    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux, darwin]
    runs-on: ubuntu-22.04
    container: golang:1.19.0-bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o gstbgen-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: gstbgen-${{ matrix.goos }}-${{ matrix.goarch }}

   